### ISSUE TITLE
react/addons?

### ISSUE THREAD

**Issue by tehfailsafe** [reactjs/react-meteor#33]
After cloning into packages/react, I was getting an error with react-addons.
`Error: Can't find npm module 'react/addons'. Did you forget to call 'Npm.depends' in package.js within the 'react' package?`

Editting package.js resolves the issue, but not what is causing it?

```javascript
Npm.depends({
  "react": reactVersion,
  "react-addons": "0.9.0",
});
```

**Comment by ryenbeatty** [comment]
I had a similar issue, after cloning and running 
```
meteor
```
I had the following error:
```
error: couldn't install npm package
While building plugin `compileJSX` in package `react`:
error: couldn't install npm package
```
So, i installed the react-tools package via npm
```
npm install -g react-tools
```
and modified packages.js to include react-tools
```
Npm.depends({
  "react": reactVersion,
  "react-tools": "0.12.2",
});
```
after this, the app started 0_o

**Comment by benjamn** [comment]
Hmm, [`react-addons` is deprecated](https://github.com/STRML/react-addons#this-package-is-deprecated), and react-tools shouldn't be necessary for anything except the compiler plugin.

@ryenbeatty can you check if `packages/react/.npm/plugin/compileJSX/node_modules/react-tools/` exists?

@tehfailsafe what version do you see in `packages/react/.npm/package/node_modules/react/package.json`?

**Comment by tehfailsafe** [comment]
@benjamn The react package lists `"version": "0.12.2"`

Now if I remove the `react-tools` from `Npm.depends` it still works and does not give the error above. Is there a path issue for the jsx compiler somehow since I had never used `react-tools` in the past?

**Comment by jongold** [comment]
I accidentally cloned `benjamn/react-meteor` rather than this repo a few days ago (typo in README, now fixed) and had up to date packages.

After fixing them, I ran into issues with `React = Npm.require("react/addons");` in [require-react.js](https://github.com/reactjs/react-meteor/blob/master/src/require-react.js); caused by a bug in Meteor https://github.com/meteor/meteor/pull/3526 . This has now been fixed but hasn't made it's way to master yet so you need to run meteor direct from a GitHub checkout

**Comment by hellogerard** [comment]
I can confirm this. I had the same error, and running the `devel` branch of meteor fixes the issue.

**Comment by qbabin** [comment]
So what is the best solution to fix this? I am also getting this

**Comment by ramsaylanier** [comment]
I'm also getting this error as well.

**Comment by tehfailsafe** [comment]
If you guys just want to get it up and working until meteor is updated, just add `react-tools` to the package.json

```
Npm.depends({
  "react": reactVersion,
  "react-tools": "0.12.2",
});
```

**Comment by ramsaylanier** [comment]
I'm assuming you mean add it to the package.js file? I have and I still get the error.

**Comment by tehfailsafe** [comment]
Yes, package.js sorry!
Strange, that worked for me. And now after the most recent update I don't have it in there anymore at all...

**Comment by hellogerard** [comment]
To get this working, do everything as normal, except that you have to run the `devel` branch of meteor:

1. Clone the meteor repo into a folder parallel to your project.
1. Make sure you are on the `devel` branch (the default, I believe)
1. In your project, instead of running `meteor`, run `../meteor/meteor`.

**Comment by vga-** [comment]
works like a charm! thanks hellogerard

**Comment by hitchcott** [comment]
Yup, working on `devel`. When will this be in main?

**Comment by qbabin** [comment]
Thanks, that works. Let's hope master gets updated soon

**Comment by ccorcos** [comment]
I cant find a devel branch...

**Comment by ccorcos** [comment]
This package is currently broken btw.

**Comment by benjamn** [comment]
@ccorcos https://github.com/meteor/meteor/tree/devel is the main development branch of the Meteor repository, which should be released soon…

**Comment by ccorcos** [comment]
Ahh. I thought you were talking about this package. How do I run meteor from the devel branch?

**Comment by hitchcott** [comment]
@ccorcos take a look at @hellogerard 's comment above.


> To get this working, do everything as normal, except that you have to run the devel branch of meteor:

> Clone the meteor repo into a folder parallel to your project.
> Make sure you are on the devel branch (the default, I believe)
> In your project, instead of running meteor, run ../meteor/meteor.

**Comment by ccorcos** [comment]
Ah. Now I get it haha. Thanks!

**Comment by cwaring** [comment]
The fix has now made it's way into the 1.0.4 RC. You can update your project using:
`meteor update --release 1.0.4-rc.0`

**Comment by reduxdj** [comment]
does not work: meteor update --release 1.0.4-rc.0

/Users/PatrickDj/.meteor/packages/meteor-tool/.1.0.42-rc.1.13ilyv9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150626-08:56:37.046(-7)? (STDERR)                        throw(ex);
W20150626-08:56:37.047(-7)? (STDERR)                              ^
W20150626-08:56:37.048(-7)? (STDERR) Error: Cannot find module 'react-tools'

=> Your application is crashing. Waiting for file change.

**Comment by reduxdj** [comment]
and still after another update:

/Users/PatrickDj/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150626-08:58:47.987(-7)? (STDERR)                        throw(ex);
W20150626-08:58:47.987(-7)? (STDERR)                              ^
W20150626-08:58:47.989(-7)? (STDERR) Error: Cannot find module 'react-tools'
W20150626-08:58:47.989(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150626-08:58:47.989(-7)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150626-08:58:47.989(-7)? (STDERR)     at Module.require (module.js:364:17)
W20150626-08:58:47.989(-7)? (STDERR)     at require (module.js:380:17)
W20150626-08:58:47.989(-7)? (STDERR)     at Object.Npm.require (/Users/PatrickDj/wild_cultivar/.meteor/local/build/programs/server/boot.js:130:18)
W20150626-08:58:47.989(-7)? (STDERR)     at app/react-meteor/plugin/compile-jsx.js:1:57
W20150626-08:58:47.990(-7)? (STDERR)     at app/react-meteor/plugin/compile-jsx.js:18:3
W20150626-08:58:47.990(-7)? (STDERR)     at /Users/PatrickDj/wild_cultivar/.meteor/local/build/programs/server/boot.js:222:10
W20150626-08:58:47.990(-7)? (STDERR)     at Array.forEach (native)
W20150626-08:58:47.990(-7)? (STDERR)     at Function._.each._.

**Comment by reduxdj** [comment]
+1, anybody have this working?

**Comment by fvpDev** [comment]
+1

**Comment by povtasci** [comment]
try this `npm install --save react-addons-pure-render-mixin`
