### ISSUE TITLE
Leaderboard example, Error: Can't find npm module 'react/addons'. Did you forget to call 'Npm.depends' in package.js within the 'reactjs_react' package?

### ISSUE THREAD

**Issue by giantelk** [reactjs/react-meteor#57]
Leaderboard example, Error: Can't find npm module 'react/addons'. Did you forget to call 'Npm.depends' in package.js within the 'reactjs_react' package?

If run `meteor update` it works, however, why won't it work as is?

```
=> Exited with code: 8                        
W20150402-22:17:02.698(-4)? (STDERR) 
W20150402-22:17:02.700(-4)? (STDERR) /Users/carlf/.meteor/packages/meteor-tool/.1.0.40.1iucsya++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150402-22:17:02.701(-4)? (STDERR)            				throw(ex);
W20150402-22:17:02.701(-4)? (STDERR)            				      ^
W20150402-22:17:02.701(-4)? (STDERR) Error: Can't find npm module 'react/addons'. Did you forget to call 'Npm.depends' in package.js within the 'reactjs_react' package?
W20150402-22:17:02.702(-4)? (STDERR)     at Object.Npm.require (/Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:147:17)
W20150402-22:17:02.702(-4)? (STDERR)     at ReactMeteorMixin.componentWillMount.self (packages/reactjs:react/src/require-react.js:1:1)
W20150402-22:17:02.702(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/packages/reactjs_react.js:48:4
W20150402-22:17:02.702(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/packages/reactjs_react.js:223:3
W20150402-22:17:02.702(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:205:10
W20150402-22:17:02.702(-4)? (STDERR)     at Array.forEach (native)
W20150402-22:17:02.702(-4)? (STDERR)     at Function._.each._.forEach (/Users/carlf/.meteor/packages/meteor-tool/.1.0.40.1iucsya++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150402-22:17:02.703(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:116:5
W20150402-22:17:05.794(-4)? (STDERR)          
W20150402-22:17:05.795(-4)? (STDERR) /Users/carlf/.meteor/packages/meteor-tool/.1.0.40.1iucsya++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150402-22:17:05.795(-4)? (STDERR) 						throw(ex);
W20150402-22:17:05.795(-4)? (STDERR) 						      ^
W20150402-22:17:05.799(-4)? (STDERR) Error: Can't find npm module 'react/addons'. Did you forget to call 'Npm.depends' in package.js within the 'reactjs_react' package?
W20150402-22:17:05.799(-4)? (STDERR)     at Object.Npm.require (/Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:147:17)
W20150402-22:17:05.799(-4)? (STDERR)     at ReactMeteorMixin.componentWillMount.self (packages/reactjs:react/src/require-react.js:1:1)
W20150402-22:17:05.799(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/packages/reactjs_react.js:48:4
W20150402-22:17:05.799(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/packages/reactjs_react.js:223:3
W20150402-22:17:05.799(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:205:10
W20150402-22:17:05.799(-4)? (STDERR)     at Array.forEach (native)
W20150402-22:17:05.799(-4)? (STDERR)     at Function._.each._.forEach (/Users/carlf/.meteor/packages/meteor-tool/.1.0.40.1iucsya++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150402-22:17:05.800(-4)? (STDERR)     at /Users/carlf/Documents/dev/meteor/react-meteor/examples/leaderboard/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
```

**Comment by dmitrijs-balcers** [comment]
This helped me: meteor update
